// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Query.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Query_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Query_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015008 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Query_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Query_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Query_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_Query_2eproto_metadata_getter(int index);
namespace JINFENG {
class Answer;
struct AnswerDefaultTypeInternal;
extern AnswerDefaultTypeInternal _Answer_default_instance_;
class Query;
struct QueryDefaultTypeInternal;
extern QueryDefaultTypeInternal _Query_default_instance_;
}  // namespace JINFENG
PROTOBUF_NAMESPACE_OPEN
template<> ::JINFENG::Answer* Arena::CreateMaybeMessage<::JINFENG::Answer>(Arena*);
template<> ::JINFENG::Query* Arena::CreateMaybeMessage<::JINFENG::Query>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace JINFENG {

// ===================================================================

class Query PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:JINFENG.Query) */ {
 public:
  inline Query() : Query(nullptr) {}
  virtual ~Query();
  explicit constexpr Query(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Query(const Query& from);
  Query(Query&& from) noexcept
    : Query() {
    *this = ::std::move(from);
  }

  inline Query& operator=(const Query& from) {
    CopyFrom(from);
    return *this;
  }
  inline Query& operator=(Query&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Query& default_instance() {
    return *internal_default_instance();
  }
  static inline const Query* internal_default_instance() {
    return reinterpret_cast<const Query*>(
               &_Query_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Query& a, Query& b) {
    a.Swap(&b);
  }
  inline void Swap(Query* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Query* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Query* New() const final {
    return CreateMaybeMessage<Query>(nullptr);
  }

  Query* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Query>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Query& from);
  void MergeFrom(const Query& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Query* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "JINFENG.Query";
  }
  protected:
  explicit Query(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Query_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestionFieldNumber = 3,
    kQuestionerFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated string question = 3;
  int question_size() const;
  private:
  int _internal_question_size() const;
  public:
  void clear_question();
  const std::string& question(int index) const;
  std::string* mutable_question(int index);
  void set_question(int index, const std::string& value);
  void set_question(int index, std::string&& value);
  void set_question(int index, const char* value);
  void set_question(int index, const char* value, size_t size);
  std::string* add_question();
  void add_question(const std::string& value);
  void add_question(std::string&& value);
  void add_question(const char* value);
  void add_question(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& question() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_question();
  private:
  const std::string& _internal_question(int index) const;
  std::string* _internal_add_question();
  public:

  // string questioner = 2;
  void clear_questioner();
  const std::string& questioner() const;
  void set_questioner(const std::string& value);
  void set_questioner(std::string&& value);
  void set_questioner(const char* value);
  void set_questioner(const char* value, size_t size);
  std::string* mutable_questioner();
  std::string* release_questioner();
  void set_allocated_questioner(std::string* questioner);
  private:
  const std::string& _internal_questioner() const;
  void _internal_set_questioner(const std::string& value);
  std::string* _internal_mutable_questioner();
  public:

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:JINFENG.Query)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> question_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr questioner_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Query_2eproto;
};
// -------------------------------------------------------------------

class Answer PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:JINFENG.Answer) */ {
 public:
  inline Answer() : Answer(nullptr) {}
  virtual ~Answer();
  explicit constexpr Answer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Answer(const Answer& from);
  Answer(Answer&& from) noexcept
    : Answer() {
    *this = ::std::move(from);
  }

  inline Answer& operator=(const Answer& from) {
    CopyFrom(from);
    return *this;
  }
  inline Answer& operator=(Answer&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Answer& default_instance() {
    return *internal_default_instance();
  }
  static inline const Answer* internal_default_instance() {
    return reinterpret_cast<const Answer*>(
               &_Answer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Answer& a, Answer& b) {
    a.Swap(&b);
  }
  inline void Swap(Answer* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Answer* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Answer* New() const final {
    return CreateMaybeMessage<Answer>(nullptr);
  }

  Answer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Answer>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Answer& from);
  void MergeFrom(const Answer& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Answer* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "JINFENG.Answer";
  }
  protected:
  explicit Answer(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_Query_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSolutionFieldNumber = 4,
    kQuestionerFieldNumber = 2,
    kAnswerFieldNumber = 3,
    kIdFieldNumber = 1,
  };
  // repeated string solution = 4;
  int solution_size() const;
  private:
  int _internal_solution_size() const;
  public:
  void clear_solution();
  const std::string& solution(int index) const;
  std::string* mutable_solution(int index);
  void set_solution(int index, const std::string& value);
  void set_solution(int index, std::string&& value);
  void set_solution(int index, const char* value);
  void set_solution(int index, const char* value, size_t size);
  std::string* add_solution();
  void add_solution(const std::string& value);
  void add_solution(std::string&& value);
  void add_solution(const char* value);
  void add_solution(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& solution() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_solution();
  private:
  const std::string& _internal_solution(int index) const;
  std::string* _internal_add_solution();
  public:

  // string questioner = 2;
  void clear_questioner();
  const std::string& questioner() const;
  void set_questioner(const std::string& value);
  void set_questioner(std::string&& value);
  void set_questioner(const char* value);
  void set_questioner(const char* value, size_t size);
  std::string* mutable_questioner();
  std::string* release_questioner();
  void set_allocated_questioner(std::string* questioner);
  private:
  const std::string& _internal_questioner() const;
  void _internal_set_questioner(const std::string& value);
  std::string* _internal_mutable_questioner();
  public:

  // string answer = 3;
  void clear_answer();
  const std::string& answer() const;
  void set_answer(const std::string& value);
  void set_answer(std::string&& value);
  void set_answer(const char* value);
  void set_answer(const char* value, size_t size);
  std::string* mutable_answer();
  std::string* release_answer();
  void set_allocated_answer(std::string* answer);
  private:
  const std::string& _internal_answer() const;
  void _internal_set_answer(const std::string& value);
  std::string* _internal_mutable_answer();
  public:

  // int32 id = 1;
  void clear_id();
  ::PROTOBUF_NAMESPACE_ID::int32 id() const;
  void set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_id() const;
  void _internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:JINFENG.Answer)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> solution_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr questioner_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr answer_;
  ::PROTOBUF_NAMESPACE_ID::int32 id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Query_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Query

// int32 id = 1;
inline void Query::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Query::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Query::id() const {
  // @@protoc_insertion_point(field_get:JINFENG.Query.id)
  return _internal_id();
}
inline void Query::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void Query::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:JINFENG.Query.id)
}

// string questioner = 2;
inline void Query::clear_questioner() {
  questioner_.ClearToEmpty();
}
inline const std::string& Query::questioner() const {
  // @@protoc_insertion_point(field_get:JINFENG.Query.questioner)
  return _internal_questioner();
}
inline void Query::set_questioner(const std::string& value) {
  _internal_set_questioner(value);
  // @@protoc_insertion_point(field_set:JINFENG.Query.questioner)
}
inline std::string* Query::mutable_questioner() {
  // @@protoc_insertion_point(field_mutable:JINFENG.Query.questioner)
  return _internal_mutable_questioner();
}
inline const std::string& Query::_internal_questioner() const {
  return questioner_.Get();
}
inline void Query::_internal_set_questioner(const std::string& value) {
  
  questioner_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Query::set_questioner(std::string&& value) {
  
  questioner_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:JINFENG.Query.questioner)
}
inline void Query::set_questioner(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  questioner_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:JINFENG.Query.questioner)
}
inline void Query::set_questioner(const char* value,
    size_t size) {
  
  questioner_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:JINFENG.Query.questioner)
}
inline std::string* Query::_internal_mutable_questioner() {
  
  return questioner_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Query::release_questioner() {
  // @@protoc_insertion_point(field_release:JINFENG.Query.questioner)
  return questioner_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Query::set_allocated_questioner(std::string* questioner) {
  if (questioner != nullptr) {
    
  } else {
    
  }
  questioner_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), questioner,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:JINFENG.Query.questioner)
}

// repeated string question = 3;
inline int Query::_internal_question_size() const {
  return question_.size();
}
inline int Query::question_size() const {
  return _internal_question_size();
}
inline void Query::clear_question() {
  question_.Clear();
}
inline std::string* Query::add_question() {
  // @@protoc_insertion_point(field_add_mutable:JINFENG.Query.question)
  return _internal_add_question();
}
inline const std::string& Query::_internal_question(int index) const {
  return question_.Get(index);
}
inline const std::string& Query::question(int index) const {
  // @@protoc_insertion_point(field_get:JINFENG.Query.question)
  return _internal_question(index);
}
inline std::string* Query::mutable_question(int index) {
  // @@protoc_insertion_point(field_mutable:JINFENG.Query.question)
  return question_.Mutable(index);
}
inline void Query::set_question(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:JINFENG.Query.question)
  question_.Mutable(index)->assign(value);
}
inline void Query::set_question(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:JINFENG.Query.question)
  question_.Mutable(index)->assign(std::move(value));
}
inline void Query::set_question(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  question_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:JINFENG.Query.question)
}
inline void Query::set_question(int index, const char* value, size_t size) {
  question_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:JINFENG.Query.question)
}
inline std::string* Query::_internal_add_question() {
  return question_.Add();
}
inline void Query::add_question(const std::string& value) {
  question_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:JINFENG.Query.question)
}
inline void Query::add_question(std::string&& value) {
  question_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:JINFENG.Query.question)
}
inline void Query::add_question(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  question_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:JINFENG.Query.question)
}
inline void Query::add_question(const char* value, size_t size) {
  question_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:JINFENG.Query.question)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Query::question() const {
  // @@protoc_insertion_point(field_list:JINFENG.Query.question)
  return question_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Query::mutable_question() {
  // @@protoc_insertion_point(field_mutable_list:JINFENG.Query.question)
  return &question_;
}

// -------------------------------------------------------------------

// Answer

// int32 id = 1;
inline void Answer::clear_id() {
  id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Answer::_internal_id() const {
  return id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Answer::id() const {
  // @@protoc_insertion_point(field_get:JINFENG.Answer.id)
  return _internal_id();
}
inline void Answer::_internal_set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  id_ = value;
}
inline void Answer::set_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:JINFENG.Answer.id)
}

// string questioner = 2;
inline void Answer::clear_questioner() {
  questioner_.ClearToEmpty();
}
inline const std::string& Answer::questioner() const {
  // @@protoc_insertion_point(field_get:JINFENG.Answer.questioner)
  return _internal_questioner();
}
inline void Answer::set_questioner(const std::string& value) {
  _internal_set_questioner(value);
  // @@protoc_insertion_point(field_set:JINFENG.Answer.questioner)
}
inline std::string* Answer::mutable_questioner() {
  // @@protoc_insertion_point(field_mutable:JINFENG.Answer.questioner)
  return _internal_mutable_questioner();
}
inline const std::string& Answer::_internal_questioner() const {
  return questioner_.Get();
}
inline void Answer::_internal_set_questioner(const std::string& value) {
  
  questioner_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Answer::set_questioner(std::string&& value) {
  
  questioner_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:JINFENG.Answer.questioner)
}
inline void Answer::set_questioner(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  questioner_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:JINFENG.Answer.questioner)
}
inline void Answer::set_questioner(const char* value,
    size_t size) {
  
  questioner_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:JINFENG.Answer.questioner)
}
inline std::string* Answer::_internal_mutable_questioner() {
  
  return questioner_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Answer::release_questioner() {
  // @@protoc_insertion_point(field_release:JINFENG.Answer.questioner)
  return questioner_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Answer::set_allocated_questioner(std::string* questioner) {
  if (questioner != nullptr) {
    
  } else {
    
  }
  questioner_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), questioner,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:JINFENG.Answer.questioner)
}

// string answer = 3;
inline void Answer::clear_answer() {
  answer_.ClearToEmpty();
}
inline const std::string& Answer::answer() const {
  // @@protoc_insertion_point(field_get:JINFENG.Answer.answer)
  return _internal_answer();
}
inline void Answer::set_answer(const std::string& value) {
  _internal_set_answer(value);
  // @@protoc_insertion_point(field_set:JINFENG.Answer.answer)
}
inline std::string* Answer::mutable_answer() {
  // @@protoc_insertion_point(field_mutable:JINFENG.Answer.answer)
  return _internal_mutable_answer();
}
inline const std::string& Answer::_internal_answer() const {
  return answer_.Get();
}
inline void Answer::_internal_set_answer(const std::string& value) {
  
  answer_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Answer::set_answer(std::string&& value) {
  
  answer_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:JINFENG.Answer.answer)
}
inline void Answer::set_answer(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  answer_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:JINFENG.Answer.answer)
}
inline void Answer::set_answer(const char* value,
    size_t size) {
  
  answer_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:JINFENG.Answer.answer)
}
inline std::string* Answer::_internal_mutable_answer() {
  
  return answer_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Answer::release_answer() {
  // @@protoc_insertion_point(field_release:JINFENG.Answer.answer)
  return answer_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Answer::set_allocated_answer(std::string* answer) {
  if (answer != nullptr) {
    
  } else {
    
  }
  answer_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), answer,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:JINFENG.Answer.answer)
}

// repeated string solution = 4;
inline int Answer::_internal_solution_size() const {
  return solution_.size();
}
inline int Answer::solution_size() const {
  return _internal_solution_size();
}
inline void Answer::clear_solution() {
  solution_.Clear();
}
inline std::string* Answer::add_solution() {
  // @@protoc_insertion_point(field_add_mutable:JINFENG.Answer.solution)
  return _internal_add_solution();
}
inline const std::string& Answer::_internal_solution(int index) const {
  return solution_.Get(index);
}
inline const std::string& Answer::solution(int index) const {
  // @@protoc_insertion_point(field_get:JINFENG.Answer.solution)
  return _internal_solution(index);
}
inline std::string* Answer::mutable_solution(int index) {
  // @@protoc_insertion_point(field_mutable:JINFENG.Answer.solution)
  return solution_.Mutable(index);
}
inline void Answer::set_solution(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:JINFENG.Answer.solution)
  solution_.Mutable(index)->assign(value);
}
inline void Answer::set_solution(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:JINFENG.Answer.solution)
  solution_.Mutable(index)->assign(std::move(value));
}
inline void Answer::set_solution(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  solution_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:JINFENG.Answer.solution)
}
inline void Answer::set_solution(int index, const char* value, size_t size) {
  solution_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:JINFENG.Answer.solution)
}
inline std::string* Answer::_internal_add_solution() {
  return solution_.Add();
}
inline void Answer::add_solution(const std::string& value) {
  solution_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:JINFENG.Answer.solution)
}
inline void Answer::add_solution(std::string&& value) {
  solution_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:JINFENG.Answer.solution)
}
inline void Answer::add_solution(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  solution_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:JINFENG.Answer.solution)
}
inline void Answer::add_solution(const char* value, size_t size) {
  solution_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:JINFENG.Answer.solution)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Answer::solution() const {
  // @@protoc_insertion_point(field_list:JINFENG.Answer.solution)
  return solution_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Answer::mutable_solution() {
  // @@protoc_insertion_point(field_mutable_list:JINFENG.Answer.solution)
  return &solution_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace JINFENG

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Query_2eproto
